### ISSUE TITLE
Schema.py error in pip standart package

### ISSUE THREAD

**Issue by andrelbol** [r4fek/django-cassandra-engine#101]
Hi, I installed django_cassandra_engine form pip, and found a bug in the schema.py file. It seems that it returns an Exception instead of Exc, and the Exception is not catched in any part of the code, so it stops. Don't know if that package is still being updated, but I found useful to inform this (couldn't do a pull request because here the code is right). Sorry for any uncovenient.

**Comment by r4fek** [comment]
Please try version 1.2.2. It should be fine there. Sorry for inconvenience ;)
