### ISSUE TITLE
Can't filter with greater operator

### ISSUE THREAD

**Issue by hptphuong** [r4fek/django-cassandra-engine#106]
I want to select all records from my table that It has ck_new is greater than 0. (ck_new is integer)

For equal 0, I use this command:
        user_daily.objects.filter(ck_new=0)
It's ok. But I can't use it with ">" operator, something like:
       user_daily.objects.filter(ck_new>0)
So could you have any solution for my case?

Please help me.

Thanks & Best Regards,

Phuong

**Comment by r4fek** [comment]
Please try using `user_daily.objects.filter(ck_new__gt=0)`
