### ISSUE TITLE
Possible to upgrade driver or remove version pinning

### ISSUE THREAD

**Issue by GeoTob** [r4fek/django-cassandra-engine#109]
Is it possible to make a new release for `cassandra-driver==3.13.0` or change the version pinning to something like `cassandra-driver>=3.10.0,<4.0.0` ? Right now I can't install the latest driver without error:

```bash
pkg_resources.ContextualVersionConflict: (cassandra-driver 3.13.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('cassandra-driver==3.12.0'), {'django-cassandra-engine'})
```

**Comment by r4fek** [comment]
Hey @GeoTob,

This is now done in current 1.4 release. Thanks!
