### ISSUE TITLE
Warnings when using celery

### ISSUE THREAD

**Issue by mehdipourfar** [r4fek/django-cassandra-engine#118]
I get the following warnings when I use this package along with Celery, as mentioned in the docs. Everything works fine but I don't understand the meaning of these warnings.

> Using datacenter 'datacenter1' for DCAwareRoundRobinPolicy (via host '127.0.0.1'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
> [2018-05-30 10:00:04,699: WARNING/ForkPoolWorker-100] Registering connection 'default' when it already exists.
> [2018-05-30 10:00:04,700: WARNING/ForkPoolWorker-100] Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['127.0.0.1'], lbp = None)

**Comment by r4fek** [comment]
Nothing to worry about. These are warnings from cassandra-driver library.
