### ISSUE TITLE
sync_cassandra only process one database

### ISSUE THREAD

**Issue by mat-green** [r4fek/django-cassandra-engine#12]
The indentation of [line 19](https://github.com/r4fek/django-cassandra-engine/blob/master/django_cassandra_engine/management/commands/sync_cassandra.py#L19) in sync_cassandra seems incorrect leading to only one django_cassandra_engine database being processed.

**Comment by r4fek** [comment]
I thinks it works. Closing.

**Comment by danandersonasc** [comment]
Agreed, it is working. Thanks!
