### ISSUE TITLE
sync_cassandra throws module not found error 

### ISSUE THREAD

**Issue by ba-la** [r4fek/django-cassandra-engine#132]
python3 ./manage.py sync_cassandra
nims-cta_1 | Traceback (most recent call last):
nims-cta_1 | File "./manage.py", line 15, in 
nims-cta_1 | execute_from_command_line(sys.argv)
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django/core/management/init.py", line 371, in execute_from_command_line
nims-cta_1 | utility.execute()
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django/core/management/init.py", line 365, in execute
nims-cta_1 | self.fetch_command(subcommand).run_from_argv(self.argv)
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
nims-cta_1 | self.execute(*args, **cmd_options)
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
nims-cta_1 | output = self.handle(*args, **options)
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 96, in handle
nims-cta_1 | self._import_management()
nims-cta_1 | File "/venv/lib/python3.6/site-packages/django_cassandra_engine/management/commands/sync_cassandra.py", line 33, in _import_management
nims-cta_1 | import_module('.management', app_name)
nims-cta_1 | File "/usr/local/lib/python3.6/importlib/init.py", line 126, in import_module
nims-cta_1 | return _bootstrap._gcd_import(name[level:], package, level)
nims-cta_1 | File "", line 994, in _gcd_import
nims-cta_1 | File "", line 971, in _find_and_load
nims-cta_1 | File "", line 941, in _find_and_load_unlocked
nims-cta_1 | File "", line 219, in _call_with_frames_removed
nims-cta_1 | File "", line 994, in _gcd_import
nims-cta_1 | File "", line 971, in _find_and_load
nims-cta_1 | File "", line 950, in _find_and_load_unlocked
nims-cta_1 | ModuleNotFoundError: No module named 'cta_app.apps.CtaAppConfig'; 'cta_app.apps' is not a package

**Comment by ba-la** [comment]
i fixed it differently i removed cta_app.apps.ctaappconfig  from INSTALLED_APPs and added in __init_file

**Comment by Manikanta8899** [comment]
@ba-la 
What exactly have you written in __init_ file ?
I have added 
INSTALLED_APPS = (
    
    'semantics.apps.SemanticsConfig',
    
)
in __init_file. But now not showing the error but unable to create models in cassandra.

**Comment by r4fek** [comment]
Please try using the old style name convention in `INSTALLED_APPS`.
