### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by kamilyrb** [r4fek/django-cassandra-engine#135]
When I switch my project from Django 2.2 to Django 3.0. I take this error:

> ERROR: django-cassandra-engine 1.5.5 has requirement Django<3,>=1.10, but you'll have django 3.0.3 which is incompatible.

Will Django 3.0 support come? Thanks.

**Comment by r4fek** [comment]
Working on it. Should be available soon :)

**Comment by kamilyrb** [comment]
Thank your, good works :)

**Comment by r4fek** [comment]
@kamilyrb I'm happy to say that support for Django 3 was added in recent version (1.6.0). Enjoy!

**Comment by kamilyrb** [comment]
Thanks a lot :)
