### ISSUE TITLE
TypeError: sql_flush() got an unexpected keyword argument 'reset_sequences'

### ISSUE THREAD

**Issue by taketrendpiotr** [r4fek/django-cassandra-engine#140]
Looks like the signature of sql_flush() [got changed](https://github.com/django/django/commit/75410228dfd16e49eb3c0ea30b59b4c0d2ea6b03#diff-f592eccb6ac9c9d865342ef59052f9c3) in Django 3.1, which makes tests fail with: 
```
File "django_cassandra_engine/management/commands/flush.py", line 26, in handle
  return super(Command, self).handle(**options)
File "django/core/management/commands/flush.py", line 49, in handle
  allow_cascade=allow_cascade)
File "django/core/management/sql.py", line 20, in sql_flush
  allow_cascade=allow_cascade,
TypeError: sql_flush() got an unexpected keyword argument 'reset_sequences'
```

Looks like 'sequences' argument isn't used, so a simple change in signature of `django_cassandra_engine.base.operations.CassandraDatabaseOperations.sql_flush`
to match Django could fix this.

**Comment by edhowler** [comment]
Waiting for this fix, thanks!

**Comment by r4fek** [comment]
Sorry for such late fix, but I finally managed to release it. Please try version 1.6.2 ;)
