### ISSUE TITLE
test database not used by code under test

### ISSUE THREAD

**Issue by lsmithso** [r4fek/django-cassandra-engine#15]
when running units tests the code under test reads and writes to the live database not the test one even though the log says the test database is created and models synced to it.

**Comment by lsmithso** [comment]
Hi: I've had some time to look at this again and discovered that the
test model used in the test cases hard codes __keyspace__ to
"test_db", so test_db is used even when the test keyspace isn't being
set up .  Setting __ keyspace__ = "db" makes all of the test fail
because django-cassandra-engine is not setting the model's keyspace to
test_db.

Would it work to have create_test_db update all the model's
__keyspace__ attrs before calling sync_table?



Rafał Furmański writes: > Hi, > Sorry for such
long wait.  > Please provide me more details about your test
environment (TEST_RUNNER, TestCase, what packages are installed, how
tests are launched, etc.). I'm unable to reproduce this and that's why
I need more information.
 > 
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/r4fek/django-cassandra-engine/issues/15#issuecomment-68434900

-- 
Les Smithson

**Comment by lsmithso** [comment]
Just to make it clear - its the django-cassandra-engine tests that set
__keyspace__ to "test_db", and that fail if __keyspace__ is set to
"db".

Rafał Furmański writes:
 > Hi,
 > Sorry for such long wait.
 > Please provide me more details about your test environment (TEST_RUNNER, TestCase, what packages are installed, how tests are launched, etc.). I'm unable to reproduce this and that's why I need more information.
 > 
 > ---
 > Reply to this email directly or view it on GitHub:
 > https://github.com/r4fek/django-cassandra-engine/issues/15#issuecomment-68434900

-- 
Les Smithson

**Comment by r4fek** [comment]
Should be fixed now. Closing.
