### ISSUE TITLE
static files not served if django_cassandra_engine is the first item in INSTALLED_APPS

### ISSUE THREAD

**Issue by nq-ebaratte** [r4fek/django-cassandra-engine#22]
The README file recommends setting django_cassandra_engine as the first app in INSTALLED_APPS; for some reason, it seems to break static file service by django.contrib.staticfiles (at least in development mode).

As a workaround, I set 'django.contrib.staticfiles' as the 1st app, then django_cassandra_engine as the 2nd. Is it safe to do so ? Is it a known issue ?

**Comment by r4fek** [comment]
django.contrib.staticfiles app overrides runserver command and django-cassandra-engine does this too.
I believe it will work as long as you use only Cassandra database in your project.
I have to find a way to deal with this problem though. Thanks for reporting!

**Comment by r4fek** [comment]
@nq-ebaratte Could you try it now?

**Comment by nq-ebaratte** [comment]
It indeed fixes the bug; though it introduces a new one:
- if django_cassandra_engine is the 1st INSTALLED_APP, the server fails at start, with the following stack trace:
```
    Traceback (most recent call last):
      File "/workspace/django/manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/workspace/venv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/workspace/venv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/workspace/venv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
        klass = load_command_class(app_name, subcommand)
      File "/workspace/venv2/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
        module = import_module('%s.management.commands.%s' % (app_name, name))
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/workspace/venv2/local/lib/python2.7/site-packages/django_cassandra_engine/management/commands/runserver.py", line 10, in <module>
        class Command(RunserverCmd):
    TypeError: Error when calling the metaclass bases
        str() takes at most 1 argument (3 given)
 ```

**Comment by r4fek** [comment]
Could you provide django version and INSTALLED_APPS list with DATABASES setting?

**Comment by nq-ebaratte** [comment]
I use Django 1.7.6, with python 2.7.8. 
INSTALLED_APPS = (
    'django.contrib.staticfiles',
    'django_cassandra_engine',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'my_application'
)

**Comment by r4fek** [comment]
And django_cassandra_engine is your default or secondary db backend?

**Comment by nq-ebaratte** [comment]
Secondary; I use an sqlite db as 'default'.

**Comment by r4fek** [comment]
Well, that's weird:

    ~/projects/django-cassandra-engine/testproject$ python manage.py runserver --settings=settings.secondary_cassandra

    Performing system checks...

    System check identified no issues (0 silenced).

    You have unapplied migrations; your app may not work properly until they are applied.
    Run 'python manage.py migrate' to apply them.

    March 11, 2015 - 14:32:03
    Django version 1.7.6, using settings 'settings.secondary_cassandra'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.

I have staticfiles app higher than django_cassandra_engine on INSTALLED_APPS list.

**Comment by nq-ebaratte** [comment]
Indeed; the new bug happens when setting 'django_cassandra_engine' as the very first installed app (I edited my previous mistaken comment)

**Comment by cuerty** [comment]
Not a fix, but for anyone else blocked by this issue: you can use [django-extension's RunServerPlus](http://django-extensions.readthedocs.org/en/latest/runserver_plus.html) until a fix is available.

**Comment by bbirand** [comment]
Same issue here..

**Comment by EzequielAdrianM** [comment]
Django is not good for serving media and static files. Try using Nginx as the proxy that handles /static/ and /media/ directories.

**Comment by rinatio** [comment]
Same issue. Placing `django_cassandra_engine` after `django.contrib.staticfiles` works as long as cassandra is a secondary DB:

```
INSTALLED_APPS = (
    'django.contrib.staticfiles',
    'django_cassandra_engine',
    ...
}
```
