### ISSUE TITLE
syncdb only sync cqlengine.Model

### ISSUE THREAD

**Issue by ehooo** [r4fek/django-cassandra-engine#23]
Hi, i try to use Cassandra as main db but when i run syncdb only cqlengine.Model class are created.
How i could for create django.db.models.Models class on DB?

Thanks

**Comment by r4fek** [comment]
Hi @ehooo,
If you want to use django_cassandra_engine along with django apps you should set up second relational database. Please take a look at examples in testproject.

**Comment by ehooo** [comment]
There is no way to make it compatible like 'django-mongodb-engine' do it?
I could write code, but i didn't found any document about who to do it
Could you help me about how i can do it?

Thanks in advance

**Comment by r4fek** [comment]
Generally if you create Django models you should put them into relational database like PostgreSQL or something. I don't have any plans to make it fully compatible.
