### ISSUE TITLE
_meta

### ISSUE THREAD

**Issue by danandersonasc** [r4fek/django-cassandra-engine#24]
Given that cqlengine models don't implement _meta, is wrapping cqlengine models to provide introspection to django by this attribute on the roadmap for this project?

**Comment by r4fek** [comment]
cqlengine is about to be merged into python-driver soon. After that we can think about it, but it is important to know, that django-cassandra-engine never meant to be fully compatible with django models.

**Comment by anhduongxanh63** [comment]
Hi r4fek,
I'm experiencing with django-cassandra-engine. Now, I want to FILTER with MULTIPLE parameters, please tell me how to do that.
Thank you :)

**Comment by Ace314159** [comment]
If django-cassandra-engine models will never implement _meta, do you have an alternative engine that does implement _meta. I am trying to use haystack elasticsearch with cassandra, but haystack requires the models to have _meta implemented. 
Thank you.

**Comment by auvipy** [comment]
@r4fek model._meta will let the cql fields to be seen through django form and admin.

**Comment by richardasaurus** [comment]
Any update on this? I'm working on a project where django models are being switched to django cassandra which seems to cause issues due to no meta api support.

**Comment by richardasaurus** [comment]
@Ace314159 FYI, there's a django haystack fork for that, for now: https://github.com/richardasaurus/django-haystack-cassandra

**Comment by richardasaurus** [comment]
I'm now implementing the _meta api support, PR coming hopefully this week.

**Comment by r4fek** [comment]
This one was merged some time ago.
