### ISSUE TITLE
Suport for Async connections

### ISSUE THREAD

**Issue by ssjunior** [r4fek/django-cassandra-engine#31]
Hi Rafał,

When using celery to process tasks, it is not possible to connect to Cassandra due to timeout. 

Maybe this is related to this observation: Just be sure to never share any Cluster, Session, or ResponseFuture objects across multiple processes. These objects should all be created after forking the process, not before.

This issue is described at: 

http://stackoverflow.com/questions/24785299/python-cassandra-driver-operationtimeout-on-every-query-in-celery-task

but is most related to the Datastax driver. 

Is there a way to create a new session inside every task worker?

Kind regards

ssjunior

**Comment by r4fek** [comment]
Hi @ssjunior, 

It is well described in documentation, so please read it and you should be OK.

**Comment by ssjunior** [comment]
@r4fek  I read the documentation and missed the FAQ. Sorry for bothering. Thank you!

**Comment by r4fek** [comment]
No problem. Perhaps I should move it to more visible place than FAQ :)
