### ISSUE TITLE
Query Help

### ISSUE THREAD

**Issue by xXPhenomXx** [r4fek/django-cassandra-engine#32]
Are there any query examples you could point me to, I am assuming that Django ORM like statements will not work with Django Cassandra Engine. For instance I am trying a simple mydatabase.objects.all() but since Cassandra is a secondary I am trying the following: mydatabase.objects.using('cassandra').all() with no luck?

When you use this package are you forced to write raw SQL queries?
Are there any query examples or sample projects using more of an ORM like structure?

Thanks

**Comment by r4fek** [comment]
Hi,
I would start from reading this: https://datastax.github.io/python-driver/object_mapper.html and this https://datastax.github.io/python-driver/cqlengine/queryset.html

Cqlengine is a little bit different from Django ORM, but it is pretty similar.
