### ISSUE TITLE
Does loaddata script supports loading data from JSON files to Cassandra database?

### ISSUE THREAD

**Issue by Aravindpogu** [r4fek/django-cassandra-engine#33]
I have a requirement to load data into cassandra db from my JSON files using Django framework. As far as I know, "manage.py loaddata" only works for relational databases but not for NoSQL class databases ( I may be wrong though). Is there any script similar to loaddata and dumpdata for loading and dumping data from/to cassandra DB from/to JSON files using django framework?

**Comment by r4fek** [comment]
Unfortunately you have to write this script on your own.
