### ISSUE TITLE
How to use list datatype using this cassandra engine.

### ISSUE THREAD

**Issue by amankumarjain** [r4fek/django-cassandra-engine#41]
from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model

Is their any method inside column object to insert list datatype in cassandra.

**Comment by amankumarjain** [comment]
from cassandra.cqlengine import columns
from cassandra.cqlengine.models import Model

Is their any method inside column object to insert list datatype in cassandra.

**Comment by thegeorgeous** [comment]
Yes,
my_list = columns.List(coulmns.Text())
