### ISSUE TITLE
CQLEngineException when running inside VPN

### ISSUE THREAD

**Issue by thegeorgeous** [r4fek/django-cassandra-engine#42]
I keep getting this error when using djang-cassandra-engine on a EC2 instance inside a VPN
```
CQLEngineException: It is required to setup() cqlengine before executing queries
```
It seems to run properly when running on a EC2 instance outside the VPN

**Comment by r4fek** [comment]
Could you run `cqlsh` on this host without any problems? This is not a bug in `django-cassandra-engine`. You might want to report this in `cassandra-driver` project or this is just an error in your configuration.

**Comment by thegeorgeous** [comment]
My bad, the version of django-cassandra-engine was a couple of versions older and the environment went into dependency hell. Figured out the compatible versions

**Comment by r4fek** [comment]
Closing then.
