### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2293:

### ISSUE THREAD

**Issue by arunpersaud** [r4fek/django-cassandra-engine#59]
Hi

when trying to build an rpm package on the open build server, I get the following error for python3

    [   35s] + python3 setup.py build
    [   35s] Traceback (most recent call last):
    [   35s]   File "setup.py", line 11, in <module>
    [   35s]     LONG_DESCRIPTION = f.read()
    [   35s]   File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    [   35s]     return codecs.ascii_decode(input, self.errors)[0]
    [   35s] UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 2293: ordinal not in range(128)
    [   35s] error: Bad exit status from /var/tmp/rpm-tmp.ZHhrmJ (%build)

Seems as if a f.read().decode('utf-8') should be used in setup.py for python3 or perhaps
open( 'README.rst'), 'r', encoding='utf-8')?

**Comment by r4fek** [comment]
Thanks for the report @arunpersaud! Could you try it now?

**Comment by arunpersaud** [comment]
Just tried it out and I also had to change the 'r' to 'br' in the open statement, but then it worked.
