### ISSUE TITLE
Batch inserts

### ISSUE THREAD

**Issue by chripede** [r4fek/django-cassandra-engine#61]
I tried using bulk_create, but that doesn't work. Are there any plans to create batch inserts?

**Comment by Joojoo1020** [comment]
any updates?
How would you save 100s of records all at once?

**Comment by chripede** [comment]
You would do something like

```
with BatchQuery() as b:
    YourModel.batch(b).create(...)
```

**Comment by Joojoo1020** [comment]
Thanks a lot for your reply 
So lets assume I get 1000s items in the form of json . 

I did the following : 
            df = pd.DataFrame(request.data)
            df["device_uuid"] = device_uuid
            df["serializer"] = None
            df["serializer"] = df.apply(
                lambda row: RawLogSerializer(data=row.to_dict()), axis=1
            )
            df.apply(
                lambda row: row["serializer"].is_valid(raise_exception=True), axis=1
            )
            logs = df.apply(lambda row: row["serializer"].save(), axis=1).tolist()
Then I am saving one by one which I know it is wrong ... 

            [l.save() for l in logs]

How would my code look like using your way .. 
Thanks again
