### ISSUE TITLE
Dependency version bump

### ISSUE THREAD

**Issue by GeoTob** [r4fek/django-cassandra-engine#89]
With the release of the new django LTS 1.11 and cassandra-driver 3.8.1, it would be cool to get an update with updated dependencies. I haven't encountered any issues after upgrading packages manually, but would probably pay to test :)

**Comment by GeoTob** [comment]
Thanks @r4fek !

**Comment by r4fek** [comment]
No problem. Please install version 1.1.0 from PyPi.
