### ISSUE TITLE
'django_cassandra_engine' isn't an available database backend.

### ISSUE THREAD

**Issue by ralpht** [r4fek/django-cassandra-engine#9]
Hi r4fek,
I am sure I am doing something wrong but I tried to setup a project using the instructions provided and I get the following error:

django.core.exceptions.ImproperlyConfigured: 'django_cassandra_engine' isn't an available database backend.

Any ideas.

Ralph

**Comment by bankifsc** [comment]
Hi,
I am getting the following error..

django.core.exceptions.ImproperlyConfigured: 'django_cassandra_engine' isn't an
available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
Error was: cannot import name 'EscapeUnicode'

my setting 
INSTALLED_APPS = (
    'django_cassandra_engine',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

DATABASES = {
    'default': {
        'ENGINE': 'django_cassandra_engine',
        'NAME': 'kkbank',
        'TEST_NAME': 'test_db',
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'replication': {
                'strategy_class': 'SimpleStrategy',
                'replication_factor': 1
            }
        }
    }
}

pip list
cassandra-driver (2.1.4.post)
cqlengine (0.21.0)
defusedxml (0.4.1)
Django (1.6.5)
django-cassandra-engine (0.2.3)
django-haystack (2.3.1)
django-image-cropping (0.8.3)
django-mobile (0.4.0)
django-nose (1.2)
django-pagination (1.0.7)
django-phonenumber-field (0.6)
django-selectable (0.7.0)
django-sendsms (0.2.2)
django-sms-gateway (1.2.1)
django-tables2 (0.14.0)
django-treebeard (2.0)
django-twilio (0.7)
djangotoolbox (1.6.2)
djappsettings (0.1.0)
easy-thumbnails (2.1)
elasticsearch (1.2.0)
futures (2.1.6)
httplib2 (0.9)
nose (1.3.3)
phonenumbers (6.2.0)
pillow (2.5.3)
pip (1.5.6)
psycopg2 (2.5.2)
python-bidi (0.3.4)
rapidsms (0.17.0)
reportlab (3.1.8)
requests (1.2.0)
setuptools (2.1)
six (1.7.3)
soappy (0.12.22)
socksipy-branch (1.01)
suds-jurko (0.6)
twilio (3.6.6)
unittest2py3k (0.5.1)
urllib3 (1.9.1)


thanks

**Comment by r4fek** [comment]
Do not use django_cassandra_engine as default database backend since you're using django apps. Please take a look at testproject with secondary cassandra settings.

**Comment by bankifsc** [comment]
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'cassandra': {
        'ENGINE': 'django_cassandra_engine',
        'NAME': 'db',
        'USER': 'user',
        'PASSWORD': 'pass',
        'TEST_NAME': 'test_db',
        'HOST': '127.0.0.1',
        'OPTIONS': {
            'replication': {
                'strategy_class': 'SimpleStrategy',
                'replication_factor': 1,
            },
            'connection': {
                'lazy_connect': True,
                'retry_connect': True,
                'consistency': ConsistencyLevel.ALL
            },
            'session': {
                'default_timeout': 15
            }
        }
    }
}

following error:

django.core.exceptions.ImproperlyConfigured: 'django_cassandra_engine' isn't an
available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    'mysql', 'oracle', 'postgresql_psycopg2', 'sqlite3'
Error was: cannot import name 'EscapeUnicode'



thanks

**Comment by wakwanza** [comment]
Django 1.8 with the last up-todate version of the cassandra-engine package  with the following DB backends declaration on OSX 10 with python2.7:

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    },
    'cassandra': {
        'ENGINE': 'django_cassandra_engine',
        'NAME': 'mydb',
        'HOST': 'xx.xx.xx.xx',
        'OPTIONS': {
            'replication': {
                'strategy_class': 'SimpleStrategy',
                'replication_factor': 1
            }
        }
    }
}

throws the following error
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Library/Python/2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Library/Python/2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Python/2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Library/Python/2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Python/2.7/site-packages/django_cassandra_engine/models.py", line 3, in <module>
    cassandra_connection = get_cassandra_connection()
  File "/Library/Python/2.7/site-packages/django_cassandra_engine/utils.py", line 106, in get_cassandra_connection
    for _alias, connection in get_cassandra_connections():
  File "/Library/Python/2.7/site-packages/django_cassandra_engine/utils.py", line 96, in get_cassandra_connections
    engine = connections[alias].settings_dict.get('ENGINE', '')
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 240, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/Library/Python/2.7/site-packages/django/db/utils.py", line 129, in load_backend
    raise ImproperlyConfigured(error_msg)
django.core.exceptions.ImproperlyConfigured: 'django_cassandra_engine' isn't an available database backend.
Try using 'django.db.backends.XXX', where XXX is one of:
    u'base', u'mysql', u'oracle', u'postgresql_psycopg2', u'sqlite3'
Error was: No module named queue
```

**Comment by r4fek** [comment]
Error was: No module named queue

Do you have `import queue` somewhere in your code?

**Comment by wakwanza** [comment]
Im using a redis  as a  sessioncache based on https://github.com/ui/django-rq  for session storage and async processing of some of the jobs. So my worker startup looks like this fro the default worker process:

```
python manage.py rqworker default
```

and the cache is as:
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

**Comment by wakwanza** [comment]
So  did some more digging .Seems its a bug with the OSX version of  six https://datastax-oss.atlassian.net/browse/PYTHON-77 as the older version has issues and defult env on OSX 10.10 is still 1.4 .Upgrade to latest 1.9 fixed the issue in updated virtualenv.
