### ISSUE TITLE
Breaks BooleanField with provided default value: can't save False via admin UI project-wide if using django-cassandra-engine in same project

### ISSUE THREAD

**Issue by ilya-khaustov** [r4fek/django-cassandra-engine#90]
Found this issue while trying to use `default` kwarg with any BooleanField for any model in the project.

After setting `default` kwarg for model field, admin UI fails to update its value to False: changing False --> True is OK, but changing True --> False doesn't work. After some investigation found this [most possible reason](https://github.com/r4fek/django-cassandra-engine/blob/master/django_cassandra_engine/apps.py#L38):

```
if (field_has_default and form.add_prefix(f.name) not in form.data and
            not getattr(form[f.name].field.widget,
                        'dont_use_model_field_default_for_empty_data', False)):
    continue
```

Condition above skips on BooleanField update when updating True --> False as field name is not present in `form.data` when widget value is not set (=False for `CheckboxInput` case). It is possible to override this behaviour by specifying `widget.dont_use_model_field_default_for_empty_data = True` for needed BooleanField, however, this looks like a poor workaround that should not be needed.

**Comment by GeoTob** [comment]
It just took me way to long to grep for something monkeypatching `django.forms.models.construct_instance`.

@r4fek is it really necessary to change the behavior of `django.forms.models.construct_instance` in  https://github.com/r4fek/django-cassandra-engine/blob/master/django_cassandra_engine/apps.py#L55 globally?

**Comment by r4fek** [comment]
@GeoTob @ilya-khaustov could you guys try with current master? I think I fixed it, but need confirmation.

**Comment by GeoTob** [comment]
@r4fek thanks, this seems to have fixed it. Would you be able to release a new version with the fix please?:)

**Comment by r4fek** [comment]
@GeoTob Version 1.1.1 released to PyPi. Enjoy :)
