### ISSUE TITLE
CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set.

### ISSUE THREAD

**Issue by wizali** [r4fek/django-cassandra-engine#91]
when I run command: ./manage.py sync_cassandra, result looks like follow: 
```
Creating keyspace db..
/home/wizali/.virutalenvs/djangodev/lib/python3.6/site-packages/cassandra/cqlengine/management.py:545: UserWarning: CQLENG_ALLOW_SCHEMA_MANAGEMENT environment variable is not set. Future versions of this package will require this variable to enable management functions.
  warnings.warn(msg)

```

**Comment by wizali** [comment]
python 3.6.1
cassandra 3.10

**Comment by r4fek** [comment]
Hey @wizali!

Thanks for reporting this. It should be fixed now.

**Comment by anithraj** [comment]
Hi r4fek,

I am facing a similar issue. But couldn't figure out how to use the apps.py file.
Do i need update Django-cassandra-engine? If Yes, Please let me know the terminal command
or
do i need to copy apps.py file installed location? If yes, how do i find the installation path ?

Thanks in advance

Thanks
Anith

**Comment by em254** [comment]
just set the environment variable to True.

> export CQLENG_ALLOW_SCHEMA_MANAGEMENT=1
