### ISSUE TITLE
Outdated docs

### ISSUE THREAD

**Issue by eavinti** [r4fek/django-cassandra-engine#96]
in the [sessions](https://r4fek.github.io/django-cassandra-engine/guide/sessions/)  is not SESSION_BACKEND. You have to use [SESSION_ENGINE](https://docs.djangoproject.com/en/1.11/ref/settings/#session-engine)

x   SESSION_BACKEND = 'django_cassandra_engine.sessions.backends.db'
✔  SESSION_ENGINE = 'django_cassandra_engine.sessions.backends.db'

**Comment by r4fek** [comment]
Hey @eavinti,
thank you very much for your contribution!
