### ISSUE TITLE
dse-driver inquiry

### ISSUE THREAD

**Issue by mbeacom** [r4fek/django-cassandra-engine#97]
Hello @r4fek!
Hope you have been well!

Are you open to a PR that would allow using the [`dse-driver`](https://github.com/datastax/python-dse-driver) or the `cassandra-driver`?
The `dse-driver` is a 1-to-1 match for existing functionality.

If you're open to it, I can submit a PR today.

Thanks

**Comment by r4fek** [comment]
Hey @mbeacom!

Sure, why not! Thank you.
